# Generated by Django 5.0.4 on 2024-12-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_add_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntome', models.CharField(max_length=255)),
                ('maladie', models.CharField(blank=True, max_length=255)),
                ('traitement', models.CharField(max_length=255)),
                ('conseil', models.TextField(blank=True, max_length=255)),
                ('date_consultation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
