# Generated by Django 5.0.4 on 2024-12-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_consultation_date_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='syntome',
            new_name='symptome',
        ),
    ]
