# Generated by Django 5.0.4 on 2024-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_syntome_consultation_symptome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='maladie_hereditaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
