# Generated by Django 5.1.3 on 2024-12-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_maladie_hereditaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='consultation',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
