# Generated by Django 5.1.3 on 2024-11-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historic_app', '0002_rename_post_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='disease',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
